# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Limpar diretorio
      shell: powershell
      run: Remove-Item -Path ${env:PATH_VALUE_DEPLOY} -Confirm:$false -Recurse -Force
    - name: Parar Servidor IIS
      run: Import-Module WebAdministration
    - run: Stop-WebSite 'hddoc.staging.net'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  
  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:  
    - name: publicar Deploy HDDOC
      run: dotnet publish -r win-x86 --sc -c Release -o c:\Publish\Azure\ 
  
  publicar:
    runs-on: self-hosted
    needs: deploy
    
    steps:
    - name: Copiando para o pasta virtual
      run: Remove-Item -Path "C:\Publish\Azure\appsettings.*", "C:\Publish\Azure\web.config" -Confirm:$false -Force
    - run: Copy-Item -Path "C:\Publish\Azure\*" -Destination "C:\inetpub\wwwroot\hddoc_Staging\" -Recurse -Force
    - name: Reiniciar Servidor IIS
      run: Import-Module WebAdministration
    - run: Start-WebSite 'hddoc.staging.net'
    - name: Test
      run: dotnet test --no-build --verbosity normal  
    
